# Generated by Django 3.2.9 on 2021-11-05 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('current_price', models.CharField(max_length=50)),
                ('old_price', models.CharField(max_length=50)),
                ('discount', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=2083)),
                ('link', models.CharField(max_length=2083)),
                ('category', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
